### PR TITLE
Allow project name with hyphen (fix for #2)

### PR DESCRIPTION
**Pull request by dawranliou**
Convert hyphens to underscores in the index.html.

### CODE REVIEW

**Comment by dawranliou** [comment]
@thheller I made this change to fix #2. Would you give me some feedback?

I ran some manual tests by creating projects with hyphens in the name:

```
lein new shadow-cljs rum-s +rum
lein new shadow-cljs reagent-s +reagent
lein new shadow-cljs om-s +om
```

And when I do `shadow-cljs watch app` I can see the hello-world app loaded.

**Comment by thheller** [comment]
I did not create this template myself and don't actually know anything about how `lein` handles this but I'm reading up on it.

The template already includes the proper name under the `{{sanitized}}` variable I believe.

**Comment by dawranliou** [comment]
Hey @thheller thanks you are right. The `{{sanitized}}` symbol used [`name-to-path`](https://github.com/technomancy/leiningen/blob/master/src/leiningen/new/templates.clj#L72) function to convert the project name to proper form. I reworked the commit and did the same testing.

**Comment by thheller** [comment]
Thanks!

**Comment by dawranliou** [comment]
My pleasure :)

**Pull request merged**
